### PR TITLE
Auto fetch fix

### LINKED ISSUE #2: /etc/cron.d/freshrss incorrect
Hi, currently the freshrss cron file in /etc/cron.d does not run properly. When interrogating the cron syslog the following error is thrown:

Error: bad username; while reading /etc/cron.d/freshrss
ERROR (Syntax error, this crontab file will be ignored)

The cron file needs to be modified to include the user who is running the job. A line like below is now successfully running for me:
*/15 * * * * root php /config/www/freshrss/app/actualize_script.php > /tmp/FreshRSS.log 2>&1

### PR DESCRIPTION
**Pull request by phendryx**
This PR changes the permissions of the freshrss cron file to 600, uses the full path for php binary and changes the syntax within the cron file (the username to run as was missing).

closes #2

### CODE REVIEW

**Comment by tobbenb** [comment]
test this please

**Comment by phendryx** [comment]
you have to do 'jenkins test this please'

**Comment by CHBMB** [comment]
jenkins test this please

**Comment by CHBMB** [comment]
@sparklyballs Want to merge this as you're the maintainer?

**Comment by CHBMB** [comment]
test this please

**Comment by CHBMB** [comment]
Well what do you know? That works too... @tobbenb was right after all....

**Pull request merged**
